openapi: 3.0.0
info:
  title: Bareng.in Server API
  version: 0.1.0
  
tags:
  - name: user
paths:
  /user/login:
    post:
      tags:
        - user
      summary: Login with email and password
      description: Login with email and password
      responses:
        '200':
          description: Returns a JWT token for the user. Valid for 24 hours.
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
        '401':
          description: Email/password incorrect.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpeted error.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - statusCode
        - error
        - message
      properties:
        statusCode:
          type: number
        error:
          type: string
        message:
          type: string
        validation:
          type: object
  securitySchemas:
    bearerJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT